# Sample Config - expected in ~/.fh-cup.toml
IP = "192.168.44.10" # Optional
FhCupDir = "/path-to-gospace/src/github.com/fheng/fh-cup" # Required - Used to determine where to put cluster persistence files/directories
CoreProjectName = "core" # Optional
CoreOpenShiftTemplates = "/path-to/fh-core-openshift-templates" # Required
MBaaSOpenShiftTemplates = "/path-to/fh-mbaas-openshift-templates" # Required
MBaaSProjectName = "mbaas1" # Optional
DockerUsername = "dockerhub-username" # Required
DockerPassword = "dockerhub-password" # Required
DockerEmail = "dockerhub-email" # Required
ClusterDomain = "cup.feedhenry.io" # Optional
DockerConfigJSONPath = "/path-to-docker-config-json/.docker/config.json" # Required
FhcTarget = "rhmap.cup.feedhenry.io" # Optional
FhcUsername = "rhmap-admin@example.com" # Optional
FhcPassword = "Password1" # Optional